from main import check_document_existance, get_doc_owner_name, get_all_doc_owners_names, add_new_shelf
from main import delete_doc, get_doc_shelf, add_new_doc
from class_Yandex_folder import YaUploader
from test_yandex_folder import Test_yandex_create_folder
from test_secretary_program import TestSecretaryUnitTest